// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSmRLxMrKW3JfJqGH_FQfl_1VPQu7Y_gA',
    appId: '1:501893671374:web:83d02d91257524d8ada39f',
    messagingSenderId: '501893671374',
    projectId: 'myflutterapp-001',
    authDomain: 'myflutterapp-001.firebaseapp.com',
    storageBucket: 'myflutterapp-001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn0yCL7Dj-WhTRXMCUmJLImTku_YWqbME',
    appId: '1:501893671374:android:4a36e079c1846849ada39f',
    messagingSenderId: '501893671374',
    projectId: 'myflutterapp-001',
    storageBucket: 'myflutterapp-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfaCE7P7KMsrJfCwXj_JXx-FKygrxMrvE',
    appId: '1:501893671374:ios:291727b977208531ada39f',
    messagingSenderId: '501893671374',
    projectId: 'myflutterapp-001',
    storageBucket: 'myflutterapp-001.firebasestorage.app',
    iosBundleId: 'com.example.myFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfaCE7P7KMsrJfCwXj_JXx-FKygrxMrvE',
    appId: '1:501893671374:ios:291727b977208531ada39f',
    messagingSenderId: '501893671374',
    projectId: 'myflutterapp-001',
    storageBucket: 'myflutterapp-001.firebasestorage.app',
    iosBundleId: 'com.example.myFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSmRLxMrKW3JfJqGH_FQfl_1VPQu7Y_gA',
    appId: '1:501893671374:web:21a544f60630ee6aada39f',
    messagingSenderId: '501893671374',
    projectId: 'myflutterapp-001',
    authDomain: 'myflutterapp-001.firebaseapp.com',
    storageBucket: 'myflutterapp-001.firebasestorage.app',
  );
}
